name: neodart
description: Extensions and principles for modern Dart development.
version: 0.1.2
homepage: https://github.com/neo-dart/neodart

environment:
  sdk: ^3.0.0

dependencies:
  lints: ^2.0.0

dev_dependencies:
  meta: ^1.8.0
  test: ^1.21.1
